package enums;

public enum Actions {
    ANT_ACTION_NONE, ANT_ACTION_GRADIENT, ANT_ACTION_UP, ANT_ACTION_DOWN, ANT_ACTION_LEFT, ANT_ACTION_RIGHT, ANT_ACTION_COLLECT, ANT_ACTION_DROP, ANT_ACTION_LOGIN;
}
