package enums;

public enum Actions {
    ANT_ACTION_NEST, ANT_ACTION_UP, ANT_ACTION_DOWN, ANT_ACTION_LEFT, ANT_ACTION_RIGHT, ANT_ACTION_COLLECT_FOOD, ANT_ACTION_COLLECT_MATERIAL, ANT_ACTION_DROP_FOOD, ANT_ACTION_DROP_MATERIAL, ANT_ACTION_LOGIN, ANT_ACTION_STEAL;
}
